name: Mirror to GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_KEY }}

      - name: Configure Git user
        run: |
          git config --global user.name "${{ secrets.GITLAB_NAME }}"
          git config --global user.email "${{ secrets.GITLAB_EMAIL }}"

      - name: Add GitLab remote
        run: |
          git remote add gitlab git@git.tu-berlin.de:${{ secrets.GITLAB_USERNAME }}/$(basename $GITHUB_REPOSITORY).git
          git fetch --all

      - name: Push all branches & tags
        run: |
          git push --all gitlab --force
          git push --tags gitlab --force
