name: Mirror to GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "${{ secrets.GITLAB_NAME }}"
          git config --global user.email "${{ secrets.GITLAB_EMAIL }}"

      - name: Add GitLab remote (HTTPS)
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@git.tu-berlin.de/${{ secrets.GITLAB_USERNAME }}/${{ github.event.repository.name }}.git
          git fetch --all

      - name: Push all branches & tags
        run: |
          git push --all gitlab --force
          git push --tags gitlab --force
